feat(DDI-781): Adjust dropdown menu position
GovAlta/ui-components pull request #1069
Opened 2023-03-21 15:48 UTC by Radha-Alberta

- Adjusted dropdown menu to show "up" when dropdown is at bottom of the page.
- Disabled scroll when dropdown menu is open

2023-03-21 16:44 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +  let _isDropUp = false;
This flag isn't required as it just indicates if the `_dropdownMenuPos` has been set

2023-03-21 16:45 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +      style={`overflow-y: auto; max-height: ${maxheight}; --bottom: ${_isDropUp ? _dropdownMenuPos : "auto"};`}
Can you format this a bit?
```
style={`
  overflow-y: auto; 
  max-height: ${maxheight}; 
  --bottom: ${_isDropUp ? _dropdownMenuPos : "auto"
};
```

2023-03-21 16:48 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    let dropdownRect = _el.getBoundingClientRect();
Depending on your editor these `let` statements will get flagged and suggest to use `const`

2023-03-21 16:51 UTC, chrisolsen requested changes
I added a few comments

2023-03-21 17:38 UTC, Radha-Alberta commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +  let _isDropUp = false;
Removed _isDropUp flag

2023-03-21 17:38 UTC, Radha-Alberta commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +      style={`overflow-y: auto; max-height: ${maxheight}; --bottom: ${_isDropUp ? _dropdownMenuPos : "auto"};`}
Done

2023-03-21 17:39 UTC, Radha-Alberta commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    let dropdownRect = _el.getBoundingClientRect();
Changed to `const`

2023-03-21 17:59 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    {
Minor nitpick: Can you use the c-style / K&R braces placement
```
if (cond) {

}
```

2023-03-21 20:21 UTC, ArakTaiRoth submitted a review, later dismissed

2023-03-22 18:35 UTC, ArakTaiRoth commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    {
@chrisolsen This has been done

2023-03-22 18:35 UTC, ArakTaiRoth approved these changes

2023-03-22 21:18 UTC, merged

2023-03-22 21:36 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.130 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.130)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.130)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-22 21:36 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.169 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.169)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.169)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-29 17:17 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.16 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.16)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-29 18:15 UTC, tzuge commented
:tada: This PR is included in version 2.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.1.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-29 18:17 UTC, tzuge commented
:tada: This PR is included in version 4.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.8.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-29 18:19 UTC, tzuge commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.8.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 22:10 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.21)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:15 UTC, tzuge commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: