chore (DDI-1265): Add docs for changing item counts on pagination
GovAlta/ui-components pull request #1076
Opened 2023-03-24 16:09 UTC by amar-ABgov

2023-03-24 19:08 UTC, Radha-Alberta commented
- [ ] After changing per page count and clicking on navigation button "Next" is resetting the items shown per page to initial value. (Video 1)

#### Video 1
https://user-images.githubusercontent.com/107069489/227617029-71fc2517-5530-4ca7-95a6-6b70f5d89120.mp4

2023-03-27 16:26 UTC, ArakTaiRoth submitted a review, later dismissed

2023-03-28 19:24 UTC, chrisolsen requested changes

2023-03-28 19:24 UTC, chrisolsen commented on libs/docs/src/components/common/Pagination.stories.mdx
> +      <div style="display: flex;">
Instead of using styles could we use the goa-block & goa-spacer, like in the storybook example below?
https://alpha.ui-components.alberta.ca/?path=/docs/utility-spacer--fill

2023-03-29 19:17 UTC, chrisolsen commented on libs/docs/src/components/common/Pagination.stories.mdx
> +            <span style={{width: 'max-content'}}>{`of ${users.length} items`}</span>
Is that text block styled with 'white-pace: no-wrap'?

2023-03-29 22:49 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Pagination.stories.mdx
> +      <goa-block>
Here you're using the standard `goa-block`, which has a default alignment of `start`, but in your react code that you're using and showing to the user, you have this `GoABlock` with an alignment of `center`.

2023-03-31 16:03 UTC, chrisolsen submitted a review, later dismissed

2023-03-31 20:50 UTC, ArakTaiRoth approved these changes

2023-04-04 19:08 UTC, chrisolsen commented on libs/docs/src/components/common/Pagination.stories.mdx
> +#### Include Per Page Dropdown
The designers like it when only the first word of a heading is capitalized :)

This header should probably also match the story name

2023-04-06 16:19 UTC, chrisolsen approved these changes

2023-04-06 16:20 UTC, merged

2023-04-06 16:20 UTC, vanessatran-ddi approved these changes

2023-04-06 18:17 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.136 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.136)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.136)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-06 18:18 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.175 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.175)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.175)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-11 21:52 UTC, tzuge commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.9.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 18:10 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.17 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.17)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.17)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 22:09 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.21)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 21:56 UTC, tzuge commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.2.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:15 UTC, tzuge commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: