fix(DDI-1302): Removed the alternative colouring for icon-overrides
GovAlta/ui-components pull request #1089
Opened 2023-04-05 23:40 UTC by ArakTaiRoth

2023-04-06 13:26 UTC, Radha-Alberta commented
- [ ] Pencil and remove icons color in Form steeper component has changed to black. (Image 1)

#### Image 1
![image](https://user-images.githubusercontent.com/107069489/230391393-188b2ef7-dc53-43d7-817a-84d0cb56413e.png)

2023-04-17 13:08 UTC, vanessatran-ddi approved these changes

2023-04-17 21:44 UTC, chrisolsen commented on libs/web-components/src/components/form-step/FormStep.svelte
> +  .status > * {
What broke this?

2023-04-17 21:44 UTC, chrisolsen requested changes
What broke this? Is there a reason that more is being added instead of reverting things to how they were when things worked.

2023-04-18 16:54 UTC, closed without merging