Production Release - April 21 / 2023
GovAlta/ui-components pull request #1104
Opened 2023-04-21 20:31 UTC by amar-ABgov

2023-04-21 20:32 UTC, vanessatran-ddi approved these changes

2023-04-21 20:39 UTC, chrisolsen requested changes
We don't want to merge these commits

2023-04-21 20:42 UTC, chrisolsen approved these changes

2023-04-21 21:36 UTC, merged

2023-04-21 21:53 UTC, tzuge commented
:tada: This PR is included in version 4.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.10.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-21 21:55 UTC, tzuge commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.10.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 18:09 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.17 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.17)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.17)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 22:08 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.21)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 21:55 UTC, tzuge commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.2.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:14 UTC, tzuge commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: