fix(DDI-1316): set checked with formcontrol value
GovAlta/ui-components pull request #1107
Opened 2023-04-25 21:07 UTC by Radha-Alberta

If checked is not passed, then checked will be set with the value of the value prop (if checked or true). Otherwise, checked will be set to false.

2023-04-27 15:54 UTC, Radha-Alberta commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    await tick();
Yes, removed it

2023-04-28 14:30 UTC, vanessatran-ddi approved these changes

2023-05-02 15:54 UTC, chrisolsen requested changes

2023-05-02 15:56 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +  };
Is this the way Angular formcontrol works?

2023-05-29 21:33 UTC, closed without merging