fix(DDI-1327): Updated angular code sample
GovAlta/ui-components pull request #1115
Opened 2023-05-05 21:55 UTC by Radha-Alberta

Updated angular code under Basic example of File Upload component

2023-05-09 19:49 UTC, ArakTaiRoth submitted a review, later dismissed

2023-05-10 18:16 UTC, vanessatran-ddi requested changes

2023-05-10 18:16 UTC, vanessatran-ddi commented on libs/docs/src/components/common/FileUpload.stories.mdx
> +      class MockUploader implements Uploader { // implement your logic to upload files}
I think the } is ignored here. 
![image](https://github.com/GovAlta/ui-components/assets/120135417/fd7d8c3d-bb74-45fc-8482-04a94ec52dd4)

Suggestion:
```
class MockUploader implements Uploader {
// implement...
}
```
so it is easier to understand on the storybook.

2023-05-10 22:56 UTC, Radha-Alberta commented on libs/docs/src/components/common/FileUpload.stories.mdx
> +      class MockUploader implements Uploader { // implement your logic to upload files}
Changed.

2023-05-10 22:59 UTC, vanessatran-ddi approved these changes

2023-05-10 23:06 UTC, ArakTaiRoth approved these changes

2023-05-11 15:30 UTC, chrisolsen requested changes

2023-05-11 15:30 UTC, chrisolsen commented on libs/docs/src/components/common/FileUpload.stories.mdx
> +        uploads: Upload[] = []; <!-- Upload is customized according to project needs, it should have the file property -->
The comments added to the snippets or in html format, not the js/ts that should probably be used

2023-05-12 17:07 UTC, Radha-Alberta commented on libs/docs/src/components/common/FileUpload.stories.mdx
> +        uploads: Upload[] = []; <!-- Upload is customized according to project needs, it should have the file property -->
Changed the comments

2023-05-18 16:51 UTC, ArakTaiRoth approved these changes

2023-05-26 16:56 UTC, chrisolsen approved these changes

2023-06-09 16:40 UTC, merged

2023-06-09 17:25 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.154 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.154)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.154)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 17:26 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.193 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.193)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.193)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 18:08 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.17 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.17)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.17)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 22:08 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.21)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 21:55 UTC, tzuge commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.2.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:02 UTC, tzuge commented
:tada: This PR is included in version 4.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.11.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:06 UTC, tzuge commented
:tada: This PR is included in version 1.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.11.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:13 UTC, tzuge commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: