feat(DDI-1328): Allow details component expand programmatically
GovAlta/ui-components pull request #1125
Opened 2023-05-29 20:52 UTC by vanessatran-ddi

### Description
End users want to expand the additional information programmatically. This PR is to add a boolean attribute "open" and a function "_toggle" that allows web component GoADetails expanded/hidden programmatically. 

### Story
[DDI-1328](https://goa-dio.atlassian.net/browse/DDIDS-1328)

### What changes:

- Add boolean "open" and function _toggle to web component GoADetails
- Update React wrapper 
- Add storybook
- Update VS Code data. 

### Screenshots:

![image](https://github.com/GovAlta/ui-components/assets/120135417/922eff5c-dcca-4803-9d2b-c50f5eb069a5)

![image](https://github.com/GovAlta/ui-components/assets/120135417/fec16502-a55d-4654-829a-6a813fdd2ce2)

2023-05-29 21:29 UTC, chrisolsen requested changes

2023-05-29 21:29 UTC, chrisolsen commented on libs/web-components/src/components/details/Details.svelte
> +      detail: { open: open === "true" }
We should probably be utilizing (listen and dispatch) the native `toggle` event that comes with the `<details>` element.

2023-05-29 22:11 UTC, vanessatran-ddi commented on libs/web-components/src/components/details/Details.svelte
> +      detail: { open: open === "true" }
It is a good suggestion. Perhaps I will dive inside it a bit to see if I can make it works. Thank you Chris!

2023-06-01 17:46 UTC, chrisolsen commented on libs/react-components/src/lib/details/details.tsx
> +  ref?: React.MutableRefObject<HTMLElement | null>;
You probably don't need the `ref` anymore

2023-06-01 18:00 UTC, chrisolsen approved these changes

2023-06-02 22:17 UTC, ArakTaiRoth approved these changes

2023-06-09 18:14 UTC, merged

2023-06-09 18:31 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.196 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.196)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.196)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-09 22:07 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.21)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 21:54 UTC, tzuge commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.2.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:01 UTC, tzuge commented
:tada: This PR is included in version 4.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.11.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:06 UTC, tzuge commented
:tada: This PR is included in version 1.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.11.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-19 22:13 UTC, tzuge commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-14 01:03 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.18 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.18)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: