DDIDS-1322 fix datetime input page crash
GovAlta/ui-components pull request #1132
Opened 2023-06-09 15:43 UTC by Radha-Alberta

2023-06-13 14:37 UTC, chrisolsen requested changes

2023-06-13 14:37 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +      value={toString(value, "yyyyyy-MM-dd'T'HH:mm:ss'")}
Is this a valid parse string?
https://date-fns.org/v2.30.0/docs/format

Is there a reason you are adding seconds to output string?

2023-06-13 14:37 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +const onDateChangeHandler = (onChange: OnDateChange, dateFormat?: string) => {
If an invalid date string is passed in I think it should just fail silently

2023-06-13 16:25 UTC, Radha-Alberta commented on libs/react-components/src/lib/input/input.tsx
> +      value={toString(value, "yyyyyy-MM-dd'T'HH:mm:ss'")}
yes it's a valid parse string for date-fns.
adding seconds in format to avoid Invalid time error. 
![image](https://github.com/GovAlta/ui-components/assets/107069489/3afbba56-25ff-4b15-ad94-14065b135368)
![image](https://github.com/GovAlta/ui-components/assets/107069489/36c8f5de-5f9a-40c9-b982-8d3cad6a9d69)

2023-06-13 16:37 UTC, Radha-Alberta commented on libs/react-components/src/lib/input/input.tsx
> +const onDateChangeHandler = (onChange: OnDateChange, dateFormat?: string) => {
yes, it's not accepting invalid dates. 
Example, I tried putting 31st Feb. if you check console in below image, it's not accepting 31st Feb
![image](https://github.com/GovAlta/ui-components/assets/107069489/e321e3cd-b955-4d3c-9cfa-4be4e1c8396b)

2023-06-19 19:41 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +const onDateChangeHandler = (onChange: OnDateChange, dateFormat?: string) => {
dateFormat is no longer needed. As I mentioned in slack the following is all you should need.

```
const onDateChangeHandler = (onChange: OnDateChange) => {
	return (name: string, value: string) => {
		if (!value) {
		  onChange(name, new Date(0));
		  return;
		}
        // new code
		const d = parseISO(value)
		if (!isNaN(d.getDate())) {
			onChange(name, d);
		}
        // end of new code
	}
}
```

2023-06-20 13:39 UTC, Radha-Alberta commented on libs/react-components/src/lib/input/input.tsx
> +const onDateChangeHandler = (onChange: OnDateChange, dateFormat?: string) => {
Changes has been updated and it's working as expected.

2023-06-21 16:47 UTC, chrisolsen requested changes

2023-06-21 16:47 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +import { format, parse, parseISO } from "date-fns";
remove this `parse` method

2023-06-21 16:47 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +      value={toString(value, "yyyy-MM-dd'T'HH:mm:ss'")}
Is there a reason you are adding seconds to the format string?

2023-06-26 19:19 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +      value={toString(value, "yyyy-MM-dd'T'HH:mm'")}
There is an extra `'` that needs to be removed

2023-06-28 17:56 UTC, Radha-Alberta commented on libs/react-components/src/lib/input/input.tsx
> +  }
My bad, I forgot to remove that code: it basically restricts user from entering more than 4 year digits, which we don't require now.

2023-06-29 19:43 UTC, closed without merging