feat: Add Tooltip component
GovAlta/ui-components pull request #1218
Opened 2023-06-14 15:11 UTC by amar-ABgov

2023-06-14 17:18 UTC, chrisolsen commented on libs/web-components/src/components/tooltip/Tooltip.svelte
> +  export let xalign: Alignment = "center"; // default to center
To better match with other component attribute naming I think this should be renamed to `halign` for `horizontal` ex (hSpacing, vSpacing)

2023-06-15 23:11 UTC, chrisolsen commented on libs/web-components/src/components/tooltip/Tooltip.svelte
> +  type Alignment = typeof Positions[number];
This should probably be `Alignment[number]`?

2023-06-20 18:03 UTC, Radha-Alberta commented
- [ ] For Android and IOS, tooltip message doesn't display full message as shows in below image.


![image](https://github.com/GovAlta/ui-components/assets/107069489/917aa967-9c7d-4b0c-a493-8fd239ec3425)

![image](https://github.com/GovAlta/ui-components/assets/107069489/dc92729d-7937-4998-88ff-6a2d938e3992)

2023-06-26 20:18 UTC, chrisolsen commented on libs/web-components/src/components/tooltip/Tooltip.svelte
> +  }
Can this be moved into the `onMount`? From what I can tell this is a one time thing, so it probably doesn't need to be in a reactive block.

2023-06-30 17:18 UTC, chrisolsen commented on libs/web-components/src/components/tooltip/Tooltip.svelte
> +  let _tooltipInstanceId: string;
Is this needed? Since this is a web component everything resided in the shadow dom, there there will be no conflict with other tooltips on the page (assuming that was the reason the random was used)

2023-07-11 15:35 UTC, Radha-Alberta commented
- [ ]  there should be no gap between the arrow and the tooltip box. There should also be 4px of space between the tooltip and the icon button.
![image](https://github.com/GovAlta/ui-components/assets/107069489/5d334eaa-698c-4625-af81-6d75c468ec38)
![image](https://github.com/GovAlta/ui-components/assets/107069489/ad65c36b-434a-4eb1-bd6f-e378e108d15e)

2023-07-12 16:52 UTC, chrisolsen requested changes

2023-07-12 16:52 UTC, chrisolsen commented on libs/web-components/src/components/tooltip/Tooltip.svelte
> +    // _showTooltipTimeout = setTimeout(() => {
delete these lines and line 94

2023-07-13 22:02 UTC, chrisolsen commented on libs/web-components/src/components/tooltip/Tooltip.svelte
> +    // _showTooltipTimeout = setTimeout(() => {
The `console.log` looks like it is still there. When you remove that there looks like there is some indentation issues that should be fixed.

2023-07-13 22:18 UTC, chrisolsen submitted a review, later dismissed

2023-07-14 00:33 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Tooltip.stories.mdx
> +    <GoATooltip content="This is a bttom tooltip" position="bottom">
You spelled `bottom` wrong here and every place below this.

2023-07-14 00:33 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Tooltip.stories.mdx
> +      content="This is a left tooltip"
To be consistent with the rest of the content, this should say "This is a left aligned bottom tooltip"

2023-07-14 00:33 UTC, ArakTaiRoth commented on libs/web-components/src/components/tooltip/Tooltip.html-data.json
> +      "name": "heading",
I think `heading` and `secondaryText` needs to be removed, and `content` added.

2023-07-14 18:26 UTC, ArakTaiRoth approved these changes

2023-07-14 18:35 UTC, chrisolsen approved these changes

2023-07-14 18:43 UTC, merged

2023-07-14 18:59 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.170 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.170)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.170)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-14 19:02 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.207 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.207)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.207)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-14 20:24 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.19 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.19)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:37 UTC, tzuge commented
:tada: This PR is included in version 2.4.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:41 UTC, tzuge commented
:tada: This PR is included in version 4.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:46 UTC, tzuge commented
:tada: This PR is included in version 1.5.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:51 UTC, tzuge commented
:tada: This PR is included in version 1.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:44 UTC, tzuge commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:49 UTC, tzuge commented
:tada: This PR is included in version 4.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:53 UTC, tzuge commented
:tada: This PR is included in version 1.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:58 UTC, tzuge commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: