DDI 1372 do dont local components
GovAlta/ui-components pull request #1239
Opened 2023-06-16 15:29 UTC by Radha-Alberta

2023-06-21 15:44 UTC, chrisolsen requested changes

2023-06-21 15:44 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/callout/Callout.tsx
> +          <div>
Not sure if this `div` is required

2023-06-21 15:44 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/callout/Callout.css
> +  display: flex;
Nesting css doesn't look like it is yet supported in all browsers
https://caniuse.com/css-nesting

2023-06-21 20:44 UTC, chrisolsen requested changes

2023-06-21 20:44 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/do-dont/DoDont.tsx
> +type DoDont = "Do" | "Dont";
We usually keep the type unions camelCase.
```
type DoDont = "do" | "dont";
```

2023-06-21 20:51 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/do-dont/DoDont.css
> +  margin-top: 0;
probably not needed

2023-06-26 19:22 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/do-dont/DoDont.tsx
>   */
We aren't using jsdoc as the previous component may have been, so this can be removed.

2023-06-26 19:27 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/do-dont/DoDont.css
> +  color: var(--goa-color-emergency-default);
I think the `Dont` will have to be lowercased to the previous casing fix.

2023-06-30 17:20 UTC, chrisolsen commented
Can we squash these two commits into one?

2023-07-04 17:12 UTC, tzuge commented
:tada: This issue has been resolved in version 4.0.0-alpha.166 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.166)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.166)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-04 17:32 UTC, tzuge commented
:tada: This issue has been resolved in version 4.0.0-alpha.167 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.167)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.167)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-04 17:33 UTC, tzuge commented
:tada: This issue has been resolved in version 1.0.0-alpha.204 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.204)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.204)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-06 16:15 UTC, chrisolsen approved these changes

2023-07-14 01:03 UTC, tzuge commented
:tada: This issue has been resolved in version 2.0.0-alpha.18 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.18)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-14 15:43 UTC, chrisolsen requested changes

2023-07-14 15:43 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/do-dont/DoDont.tsx
> +type DoDont = "Do" | "Dont";
It doesn't look like there was a change made

2023-07-14 15:43 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/tabs/Tabs.tsx
> +    <SCTab className={props.active ? "active" : undefined} onClick={() => selectTab()}>
This is unnecessary.

2023-07-14 15:43 UTC, chrisolsen commented on libs/shared/storybook-common/src/lib/tabs/Tabs.tsx
> +          activeChildren().map((child: React.ReactNode, index: number) => {
For these checks on whether the element is a valid react element (not sure if they are needed), a better approach would be do perform a `filter` then a `map`

2023-07-14 17:33 UTC, ArakTaiRoth commented
Closing as this has been opened on the documentation repo

2023-07-14 17:33 UTC, closed without merging

2023-07-14 19:01 UTC, tzuge commented
:tada: This issue has been resolved in version 1.0.0-alpha.23 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.23)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.23)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-17 20:05 UTC, tzuge commented
:tada: This issue has been resolved in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-17 20:07 UTC, tzuge commented
:tada: This issue has been resolved in version 1.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.12.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-17 20:08 UTC, tzuge commented
:tada: This issue has been resolved in version 1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.4.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:38 UTC, tzuge commented
:tada: This issue has been resolved in version 2.4.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:43 UTC, tzuge commented
:tada: This issue has been resolved in version 4.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:47 UTC, tzuge commented
:tada: This issue has been resolved in version 1.5.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:52 UTC, tzuge commented
:tada: This issue has been resolved in version 1.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:45 UTC, tzuge commented
:tada: This issue has been resolved in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:50 UTC, tzuge commented
:tada: This issue has been resolved in version 4.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:54 UTC, tzuge commented
:tada: This issue has been resolved in version 1.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:59 UTC, tzuge commented
:tada: This issue has been resolved in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: