feat(1136): Add Tabs component
GovAlta/ui-components pull request #1249
Opened 2023-06-22 14:28 UTC by vanessatran-ddi

**1. What this code change do:**

- Add Tabs and TabItem under web-components
- Add demo route for Tabs in Angular and React demo
- Add a new story book page for Tabs component
- Unit tests added 

**Screenshots**
![image](https://github.com/GovAlta/ui-components/assets/120135417/2ed24f82-4832-488b-937e-20ee5fa36d49)

MOBILE VERSION:

![image](https://github.com/GovAlta/ui-components/assets/120135417/80b49d96-5acc-4e0b-87a7-6a88ae594919)

DESKTOP:

![image](https://github.com/GovAlta/ui-components/assets/120135417/cf2653e2-3132-4843-a677-e96965d81d7b)

- **2. Make sure that you've checked the boxes below before you submit PR:**

- [x] I have read and followed the [contribution guidelines](../../contributing.md)
- [x] I have run a build locally.
- [x] I have ran unit tests locally.
- [x] I have tested the functionality.

**3. Which issue and JIRA item does this PR fix (optional)**
#1136 
**4. Additional notes for the reviewer**
- Tabs component supports for accessibility guideline at [w3](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/)

## Reviewer Checklist

- [ x] Appropriate unit test coverage.
- [x] [Coding Standards](../contribution_guidelines/coding_standards.md) followed.

2023-06-22 14:29 UTC, vanessatran-ddi commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +<button
For Reviewers: this follows the tutorial of accessibility at https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/

2023-06-23 14:30 UTC, Radha-Alberta commented
**Keyboard Functions:**
- [ ] Right Arrow: If focus is on the last tab, does not moves focus to the first tab.
- [ ] Left Arrow: If focus is on the first tab, does not moves focus to the last tab.
![image](https://github.com/GovAlta/ui-components/assets/107069489/28fba5b0-712d-42ea-b20e-1a6d6a7e87c0)



**UI**
- [ ] Profile tabs padding should be 16px on both side (only right padding is 16px).
- [ ] Gap between 2 tabs should be 32px. (current gap 0px).
![image](https://github.com/GovAlta/ui-components/assets/107069489/a687c0c8-d97e-44c1-8410-d49ad9d1a57f)
https://www.loom.com/share/f2835ca14b224134874146f91b514e02?sid=9e26c088-e5f0-4964-8350-b2e3a90d053f

**Accessibility:**
- [ ] Chrome OS on Browser: while hovering the tabs, it does not speak for 1st tab (Profile).


https://github.com/GovAlta/ui-components/assets/107069489/4c137883-c046-4aca-85e6-68c2eb3d279d

2023-06-26 19:17 UTC, chrisolsen requested changes

2023-06-26 19:17 UTC, chrisolsen commented on libs/react-components/src/lib/tab-item/tab-item.tsx
> +      "goa-tab-item": WCProps & React.HTMLAttributes<HTMLElement>;
I find that `tab-item` seems to be redundant. I think `goa-tab` works better. We should have a discussion on this.

2023-06-26 19:17 UTC, chrisolsen commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +  on:click
I don't think this is necessary and adds some confusion to why this is being done.

2023-06-26 19:17 UTC, chrisolsen commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +    position: relative;
What is the reason this is `display: relative` with a `z-inde x`

2023-06-26 19:17 UTC, chrisolsen commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +    border-left: var(--goa-border-width-s) solid var(--goa-color-greyscale-200);
I don't like having mobile specific styles in the "base" class, for the reason that after that you have to remember to override that style in the other class definitions for different media/container sizes.

2023-07-05 17:53 UTC, vanessatran-ddi commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +    position: relative;
It is a good catch. In my memory, I was doing that to make sure the tab is on the top of the stack to be visible. However now when I re-test everything without z-index it looks good still. I will remove it.

2023-07-05 17:54 UTC, vanessatran-ddi commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +    border-left: var(--goa-border-width-s) solid var(--goa-color-greyscale-200);
I was doing that with the purpose to make it mobile first. It just happened that our component has different padding sizes for mobile and desktop. 
As discussed in slack, we can sync after your touch base with Thom regarding it.

2023-07-05 19:51 UTC, vanessatran-ddi commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +    position: relative;
I think I remember why now. 
![image](https://github.com/GovAlta/ui-components/assets/120135417/d06e4724-c8bf-4d61-8f47-e530e04e02b4)
I need to make z-index here just to make sure when it is hover, active or focus, the border px width is higher, which is kind of hidden by the tabpanel border width 1px below. 

Without z-index it will be: 
![image](https://github.com/GovAlta/ui-components/assets/120135417/ca4ca931-b940-4cd4-adfa-b0530b724fce)

The focus outline is hidden by the tabpanel border below.

2023-07-07 15:44 UTC, vanessatran-ddi commented on libs/web-components/src/components/tab-item/TabItem.svelte
> +    border-left: var(--goa-border-width-s) solid var(--goa-color-greyscale-200);
I updated the CSS and separate mobile/desktop CSS, with a base CSS like we discussed.

2023-07-07 15:45 UTC, vanessatran-ddi commented on libs/react-components/src/lib/tab-item/tab-item.tsx
> +      "goa-tab-item": WCProps & React.HTMLAttributes<HTMLElement>;
I changed the name from "goa-tab-item" to "goa-tab".

2023-07-07 15:47 UTC, vanessatran-ddi commented
> **Keyboard Functions:**
> 
> * [x]  Right Arrow: If focus is on the last tab, does not moves focus to the first tab.
> * [x]  Left Arrow: If focus is on the first tab, does not moves focus to the last tab.
>   ![image](https://user-images.githubusercontent.com/107069489/248293099-28fba5b0-712d-42ea-b20e-1a6d6a7e87c0.png)
> 
> **UI**
> 
> * [x]  Profile tabs padding should be 16px on both side (only right padding is 16px).
> * [x]  Gap between 2 tabs should be 32px. (current gap 0px).
> * [x]  the bottom border for hover and active should be 4px.
> * [x]  the focus state should also include the grey bottom border like the hover state.
> * [x]  currently the position of the active and hover bottom border is correctly positioned on the first tab, and is lower on all other tabs
> * [x]  there is extra 16px padding on the left side of all tabs, making the tab content off centre
>   - it should be space-m for padding left and right within the tab
>   ![image](https://user-images.githubusercontent.com/107069489/248292300-a687c0c8-d97e-44c1-8410-d49ad9d1a57f.png)
>   https://www.loom.com/share/f2835ca14b224134874146f91b514e02?sid=9e26c088-e5f0-4964-8350-b2e3a90d053f
> 
> **Accessibility:**
> 
> * [x]  Chrome OS on Browser: while hovering the tabs, it does not speak for 1st tab (Profile).
> 
>  Tabs_Accessibility_Windows_Chrome.mp4

I fixed the above. The last point "Accessibility", we agree that NVDA should speak when we focus on the tab (not hover)

2023-07-07 21:05 UTC, Radha-Alberta commented
- [ ] active focus always does have blue underline, not grey

- [ ] It looks like the tab order should be:
            - focus active tab
            - can use arrow keys left and right to change tab
            - but next tab key goes to content
            - then next tab key goes to next part of page
https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/


![image](https://github.com/GovAlta/ui-components/assets/107069489/59107086-4eb2-4196-80b9-98fdbbf86d65)
![image](https://github.com/GovAlta/ui-components/assets/107069489/7dd84741-a00d-4dd9-aca3-74ba88830147)

2023-07-10 20:51 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Tabs.stories.mdx
> +#### GoATabItem Properties
I think we changed the name to just `GoATab` instead of `GoATabItem`

2023-07-10 20:51 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Tabs.stories.mdx
> +      <GoATable variant="relaxed">
Is there a specific reason we decided to show a table in this tab? If not, I would suggest changing the content to just a paragraph or something, it would make the code people are copying soooo much simpler.

2023-07-10 20:51 UTC, ArakTaiRoth commented on libs/react-components/src/lib/tab/tab.tsx
> +  heading?: string | React.ReactNode;
Because we're using `children` below, I'm pretty sure we need to add `children` to the properties as well, otherwise we have problems with more modern versions of React. Refer to your `tabs` component, as that does it properly.

2023-07-10 20:51 UTC, ArakTaiRoth commented on libs/web-components/src/components/tab/Tab.html-data.json
> +      "name": "content",
This isn't accurate. There is no content `slot`, you just put content in between the opening and closing tag.

2023-07-10 21:17 UTC, ArakTaiRoth submitted a review, later dismissed

2023-07-11 04:43 UTC, chrisolsen reviewed
In this review there are a few things that I saw, but after looking at things a little more I think things could be simplified a bit.

2023-07-11 15:50 UTC, closed without merging