fix(#1145): added onfocus and onblur event
GovAlta/ui-components pull request #1262
Opened 2023-07-05 16:49 UTC by Radha-Alberta

2023-07-07 01:36 UTC, chrisolsen commented on libs/web-components/src/components/input/Input.svelte
> +    this.dispatchEvent(new CustomEvent("_onFocus", { composed: true }));
Following our event naming convention, custom event should be `_focus` and `_onBlur` should be `_blur`

2023-07-07 20:26 UTC, ArakTaiRoth commented
Issues:

- [ ] React - Both focus and blur events fire twice when activated
- [ ] React and Angular - There are no event details sent back when activating the event like the change event. Send back the name of the component, and the value in the component, just like the change event.

2023-07-19 17:13 UTC, chrisolsen requested changes

2023-07-19 17:13 UTC, chrisolsen commented on libs/web-components/src/components/input/Input.svelte
> +    }, debounce);
Is there a reason you are using a debounce here? Debounce is something you would use when you have continuous input, but focus and blur doesn't happen as often.

2023-07-19 19:24 UTC, Radha-Alberta commented on libs/web-components/src/components/input/Input.svelte
> +    }, debounce);
while clean up, I missed this one

2023-07-19 19:26 UTC, Radha-Alberta commented on libs/docs/src/components/common/Input.stories.mdx
> +    type="() => void"
I updated the code, However this will remain same for angular as we're just using '$event' to get event.detail [ just like onChange ]

2023-07-19 19:34 UTC, chrisolsen requested changes

2023-07-19 19:34 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +      onBlur={onNumberChange}
You will need to use the onFocus and onBlur here

2023-07-19 21:39 UTC, chrisolsen requested changes

2023-07-19 21:39 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +type onFocusBlurEvent = (name: string, value: string) => void;
This event should not include two different events. Delete this and use the blur and focus event you created below.

2023-07-19 21:39 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +type OnBlurChange = (name: string, value: number) => void;
These should just be named OnFocus and OnBlur, since nothing is changing.

2023-07-19 21:39 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +  };
Remove "Change"

2023-07-20 14:01 UTC, Radha-Alberta commented on libs/react-components/src/lib/input/input.tsx
> +type onFocusBlurEvent = (name: string, value: string) => void;
I created onFocus and onBlur events, However, we can't use below event as the value type is different for below onFocusType.

2023-07-20 14:44 UTC, chrisolsen commented on libs/react-components/src/lib/input/input.tsx
> +    const onFocusListener = (e: unknown) => {
For consistency within this file this should be `focusListener` and onBlurListener should be `blurListener`

2023-07-20 15:30 UTC, chrisolsen submitted a review, later dismissed

2023-07-20 16:12 UTC, chrisolsen commented on libs/docs/src/components/common/Input.stories.mdx
> +    description="onFocus function triggers when an element receives focus"
This should be changed to
`Function invoked when an element receives focus`

The same is true for the onBlur prop

2023-07-20 17:25 UTC, chrisolsen approved these changes

2023-07-20 17:32 UTC, ArakTaiRoth approved these changes

2023-07-20 17:33 UTC, merged

2023-07-20 17:52 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.173 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.173)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.173)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-20 17:53 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.210 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.210)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.210)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:37 UTC, tzuge commented
:tada: This PR is included in version 2.4.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:41 UTC, tzuge commented
:tada: This PR is included in version 4.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:46 UTC, tzuge commented
:tada: This PR is included in version 1.5.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:50 UTC, tzuge commented
:tada: This PR is included in version 1.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:44 UTC, tzuge commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:48 UTC, tzuge commented
:tada: This PR is included in version 4.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:53 UTC, tzuge commented
:tada: This PR is included in version 1.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:57 UTC, tzuge commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: