feat: Add Tabs component
GovAlta/ui-components pull request #1271
Opened 2023-07-11 21:13 UTC by vanessatran-ddi

fixes #1136

2023-07-12 14:05 UTC, Radha-Alberta commented
- [ ] Gap between content and badge should be 8px, currently it's 1rem.
- [ ] If focus is on the last tab, moves focus to the first tab.
- [ ] If focus is on the first tab, moves focus to the last tab.
- [ ] accessibility should not speak onHover of Tab.

![image](https://github.com/GovAlta/ui-components/assets/107069489/e56a62c3-26e9-4dd8-8baf-6b0a76afa52d)
![image](https://github.com/GovAlta/ui-components/assets/107069489/24ca3c52-03c0-4fc3-b6bd-2961cf04cefc)

2023-07-12 21:33 UTC, chrisolsen commented on libs/web-components/src/components/tabs/Tabs.svelte
> +      case 'ArrowRight':
Do we want to add `case 'ArrowDown':` here to match the case statements above or remove the `ArrowUp` above? I added the up/down arrows to make the arrow keys make more sense on the mobile version, but I wasn't sure that is an a11y thing or not.

2023-07-12 22:20 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +      case 'ArrowRight':
I miss this point. According to our figma and also w3 accessbility page, we handle only left and right arrow. However, W3 design for mobile view is similar to desktop view, while our mobile design is similar to side menu bar, which arrow up and down make sense. 
@twjeffery how do you think? I think arrow up and down will make sense for mobile, so we can combine 2 of them together: arrow up OR arrow left to move to previous tab, arrow-down OR arrow right to move to next tab.

2023-07-13 14:35 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +      case 'ArrowRight':
@chrisolsen I added ArrowDown back.

2023-07-14 13:37 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +  export let current: number = 1;
@amar-ABgov I checked with FormStepper (similar logic), we use 'step', also checked with pagination , we use 'pagenumber'
I will prevent 'index' because we start from 1 , so I will use 'tab' in this case to make it similar with the rest.

2023-07-14 17:21 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +
@amar-ABgov I handled the reactive property "tab", also dispatch with _change. Thank you for your catch!

2023-07-14 17:28 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +      _tabItems = [..._rootEl.querySelectorAll("goa-tab")] as Element[]; // for unit tests
@amar-ABgov I set _tabItems = [] when init it. For here, _tabItems will be an array of undefined if this doesn't return anything. [undefined], so it still works with the rest.

2023-07-14 17:29 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +    _rootEl.addEventListener("keydown", onKeyDown);
@amar-ABgov I make functions to be clearer now with removeKeyboardEventListeners(), and put it under the destroy. When we remove "focus", it should remove "keydown" too.

2023-07-14 17:29 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/tabs.spec.ts
> +describe("Tabs", () => {
I added 2 unit tests to cover this case. Thank you!

2023-07-14 17:50 UTC, chrisolsen requested changes

2023-07-14 17:50 UTC, chrisolsen commented on libs/web-components/src/components/tabs/Tabs.svelte
> +  export let tab: number = 1; // 1-based
I noticed this was changed from `current` which better describes what it is, and I think `tab` is even less descriptive. `currenttab` or `activetab` makes more sense.

2023-07-14 17:50 UTC, chrisolsen commented on libs/web-components/src/components/tabs/Tabs.svelte
> +
The active tab would only be set by the developer initially, after that we control that value and that value should no longer be set externally.

2023-07-14 17:50 UTC, chrisolsen commented on libs/web-components/src/components/tabs/Tabs.svelte
> +      _tabItems = [..._rootEl.querySelectorAll("goa-tab")] as Element[]; // for unit tests
`_tabItems` is being always being set in the snippet above (either in the if or the else), so initializing it before doesn't have an effect.

2023-07-14 17:50 UTC, chrisolsen commented on libs/web-components/src/components/tabs/Tabs.svelte
> +    _rootEl.addEventListener("keydown", onKeyDown);
Any listeners set on elements within the component will get auto deleted when the component is deleted. It is `window` events that need to be cleaned up.

2023-07-14 19:21 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +
@amar-ABgov  and @chrisolsen 
After discussion with @chrisolsen and @amar-ABgov , we agree that we won't add reactive property "tab".

2023-07-14 19:22 UTC, vanessatran-ddi commented on libs/web-components/src/components/tabs/Tabs.svelte
> +  export let tab: number = 1; // 1-based
@chrisolsen As we discussed, we will change the name to "initialtab"

2023-07-14 19:50 UTC, chrisolsen approved these changes

2023-07-14 20:08 UTC, merged

2023-07-14 20:24 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.19 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.19)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-14 20:25 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.171 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.171)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.171)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-14 20:25 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.208 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.208)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.208)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:37 UTC, tzuge commented
:tada: This PR is included in version 2.4.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:41 UTC, tzuge commented
:tada: This PR is included in version 4.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:46 UTC, tzuge commented
:tada: This PR is included in version 1.5.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-01 21:51 UTC, tzuge commented
:tada: This PR is included in version 1.13.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:44 UTC, tzuge commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.4.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:48 UTC, tzuge commented
:tada: This PR is included in version 4.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:53 UTC, tzuge commented
:tada: This PR is included in version 1.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.13.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-02 20:58 UTC, tzuge commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.5.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: