feat(#1176): Description for radio and checkbox inputs
GovAlta/ui-components pull request #1311
Opened 2023-08-10 15:40 UTC by amar-ABgov

2023-08-10 17:42 UTC, chrisolsen requested changes

2023-08-10 17:42 UTC, chrisolsen commented on libs/web-components/src/components/radio-group/RadioGroup.svelte
> +        </div>
minor indentation fix

2023-08-10 17:42 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    margin-top: 4px;
Maybe use 0.25rem instead?

2023-08-10 17:42 UTC, chrisolsen commented on libs/web-components/src/components/radio-group/RadioGroup.svelte
> +
Though not required, just a minor whitespace removal

2023-08-10 17:42 UTC, chrisolsen commented on libs/web-components/src/components/radio-group/RadioGroup.svelte
> +    margin-top: 4px;
Maybe change this to `rem` as well

2023-08-14 17:08 UTC, Radha-Alberta commented
- [ ] **Issue-1:** Clicking on description should not make selection.
- [ ] **Issue-2:** Checkbox should not lose focus on toggle.
- [ ] **Issue-3:** Radio button & Checkbox should also announce the text and description, currently it announces the radio-group/checkbox-group
- [ ] **Issue-4:** the checkbox should not have a grey border on the selected state
- [ ] **Issue-5:** regarding the focus states and hover states: When a radio item or checkbox is focused, there should not be a hover state (it should remain focused state until not focused anymore)


**Radio Button Accessibility (Issue-3) :**
- **Current**:  description  radio button  unavailable  checked  6 of 18
- **Expected**: Home Delivery  radio button  checked  2 of 3

**Checkbox Accessibility (Issue-3) :**
- **Current:** Description  check box  not checked
- **Expected:** Mustard  check box  checked

**Steps to Reproduce, CheckBox: (Issue-5)**
1. press tab and focus on checkbox
2. hover over the checked checkbox
3. here, background-color should not change (there should not be a hover state)

**Steps to Reproduce, Radio: (Issue-5)**
1. press tab and focus on radio button
2. hover over the checked radio button
3. here, background-color should not change and focus should be active ( there should not be a hover state )


**Issue-4:**
- Expected:
![image](https://github.com/GovAlta/ui-components/assets/107069489/5c692f21-0c56-4273-bdbd-9b088817b1b5)

- Current:
![image](https://github.com/GovAlta/ui-components/assets/107069489/093a3015-c1d4-4a18-bfb6-372123e555d9)
![image](https://github.com/GovAlta/ui-components/assets/107069489/f0c2b8bd-9004-40c8-b874-10304fd42994)

2023-08-23 17:46 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
>      border: 1px solid var(--goa-color-emergency-default);
1px = --goa-border-width-s (there are a couple other places this could be changed)

2023-08-23 21:21 UTC, chrisolsen approved these changes

2023-08-28 18:37 UTC, vanessatran-ddi approved these changes

2023-08-28 18:39 UTC, merged

2023-08-29 21:47 UTC, tzuge commented
:tada: This PR is included in version 2.5.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.5.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.5.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-29 21:49 UTC, tzuge commented
:tada: This PR is included in version 4.14.0-alpha.2 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.14.0-alpha.2)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.14.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-29 21:50 UTC, tzuge commented
:tada: This PR is included in version 1.14.0-alpha.2 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.14.0-alpha.2)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.14.0-alpha.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-31 21:39 UTC, tzuge commented
:tada: This PR is included in version 4.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.14.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-31 21:42 UTC, tzuge commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.14.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: