Adding disabled and width attributes to the date-picker
GovAlta/ui-components pull request #1546
Opened 2024-01-02 21:23 UTC by hassananv

2024-01-03 17:38 UTC, chrisolsen requested changes

2024-01-03 17:38 UTC, chrisolsen commented on libs/react-components/src/lib/date-picker/date-picker.tsx
> +  disabled = false,
The default value will be set within the svelte component, so the `= false` can be removed here.

2024-01-03 17:38 UTC, chrisolsen commented on libs/web-components/src/components/date-picker/DatePicker.svelte
> +    await tick();
Is this fixing an angular binding issue?

2024-01-03 17:38 UTC, chrisolsen commented on libs/web-components/src/components/date-picker/DatePicker.svelte
> +    if (!isDisabled) {
Can you change this to
```
_showPopover = !isDisabled;
```

2024-01-03 18:03 UTC, hassananv commented on libs/web-components/src/components/date-picker/DatePicker.svelte
> +    await tick();
Yes, without this line, Angular binding data does not take effect.

2024-01-03 19:39 UTC, chrisolsen commented on libs/react-components/src/lib/date-picker/date-picker.tsx
> +  disabled?: boolean;
The only other thing that is need are some tests.
- validate that the disabled prop is in fact disabling it i.e. doesn't respond to user events (more difficult)
- validate that the width is binding to the internal text input (easy)

2024-01-08 20:56 UTC, ArakTaiRoth commented
Re-opened this as we can use this work and just need to add to it.

2024-09-04 22:41 UTC, ArakTaiRoth commented
Closing this PR, as part of the work for disabled has been done in this [PR](https://github.com/GovAlta/ui-components/pull/2091)

2024-09-04 22:41 UTC, closed without merging