fix(#1639): web-components module file update
GovAlta/ui-components pull request #1649
Opened 2024-02-20 17:46 UTC by amar-ABgov

2024-02-20 18:29 UTC, ArakTaiRoth approved these changes

2024-02-20 18:34 UTC, chrisolsen approved these changes

2024-02-20 18:49 UTC, chrisolsen requested changes

2024-02-20 18:49 UTC, chrisolsen commented on libs/web-components/package.json
>    "private": true,
Can you also remove this line (#14)

2024-02-21 16:40 UTC, chrisolsen approved these changes

2024-02-21 16:41 UTC, merged

2024-02-21 21:37 UTC, tzuge commented
:tada: This PR is included in version 1.17.0-alpha.11 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.17.0-alpha.11)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.17.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-21 21:37 UTC, tzuge commented
:tada: This PR is included in version 2.6.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.6.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.6.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-21 23:59 UTC, tzuge commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.6.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: