NOT READY - fix(#2108): dropdown width related issues
GovAlta/ui-components pull request #2179
Opened 2024-10-08 16:10 UTC by syedszeeshan

# Before (the change)

# After (the change)

## Make sure that you've checked the boxes below before you submit the PR

- [ ] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [ ] I have tested the functionality in both React and Angular.

## Steps needed to test

2024-10-10 22:17 UTC, lizhuomeng71 commented
The popover's maximum width remains fixed at 320px, even when the dropdown width is set to a percentage value, leading to inconsistent sizing.

Please see this example
```

    <GoAFormItem label="Dropdown" requirement="optional">
      <GoADropdown
        name="dropdown"
        width="50%"
        placeholder="Select a value"
        onChange={function (name: string, values: string[] | string): void {
          throw new Error("Function not implemented. ");
        }}
      >
        <GoADropdownItem key="_none_" name="none" value="" label="None" />
        <GoADropdownItem key="_some_" name="some" value="" label="Some Long Value Some Long Value" />
      </GoADropdown>
    </GoAFormItem>
```

2024-10-11 17:21 UTC, syedszeeshan commented
> The popover's maximum width remains fixed at 320px, even when the dropdown width is set to a percentage value, leading to inconsistent sizing.
> 
> Please see this example
> 
> ```
> 
>     <GoAFormItem label="Dropdown" requirement="optional">
>       <GoADropdown
>         name="dropdown"
>         width="50%"
>         placeholder="Select a value"
>         onChange={function (name: string, values: string[] | string): void {
>           throw new Error("Function not implemented. ");
>         }}
>       >
>         <GoADropdownItem key="_none_" name="none" value="" label="None" />
>         <GoADropdownItem key="_some_" name="some" value="" label="Some Long Value Some Long Value" />
>       </GoADropdown>
>     </GoAFormItem>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7528736/375561672-295a2263-9c04-4168-8227-8fb3d5446166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Njc1MTIsIm5iZiI6MTcyODY2NzIxMiwicGF0aCI6Ii83NTI4NzM2LzM3NTU2MTY3Mi0yOTVhMjI2My05YzA0LTQxNjgtODIyNy04ZmIzZDU0NDYxNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTcyMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI0MTVlZDIwZDU3YzgxMTFlZmU1NDMwYjBkYzRjYTc1M2VkMmM3NDNkNDgzN2M2ZTA3MGY0ZTg1ZWNlYmRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T1URAl5sUwsoQp4dL_AqnccoVCtbHwE0Zr6dJ2c0BOQ)

@lizhuomeng71 Thanks, I have fixed it and updated teh PR, ready for testing.

2024-10-11 17:26 UTC, syedszeeshan commented
> The popover's maximum width remains fixed at 320px, even when the dropdown width is set to a percentage value, leading to inconsistent sizing.
> 
> Please see this example
> 
> ```
> 
>     <GoAFormItem label="Dropdown" requirement="optional">
>       <GoADropdown
>         name="dropdown"
>         width="50%"
>         placeholder="Select a value"
>         onChange={function (name: string, values: string[] | string): void {
>           throw new Error("Function not implemented. ");
>         }}
>       >
>         <GoADropdownItem key="_none_" name="none" value="" label="None" />
>         <GoADropdownItem key="_some_" name="some" value="" label="Some Long Value Some Long Value" />
>       </GoADropdown>
>     </GoAFormItem>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7528736/375561672-295a2263-9c04-4168-8227-8fb3d5446166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Njc3MzAsIm5iZiI6MTcyODY2NzQzMCwicGF0aCI6Ii83NTI4NzM2LzM3NTU2MTY3Mi0yOTVhMjI2My05YzA0LTQxNjgtODIyNy04ZmIzZDU0NDYxNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTcyMzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2M2Y5MTk4YjMwYWRmZGM5ZDY2ZDRlZjhhOGQzZWQxNjQ4OTBhMjUzN2ZkMDkzNjgzYTY2ZGVkZmRlMWFkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.upxs4sfbeeXfedo7RgjPPLYHfu2yppBmS2Gm_LXo_Bk)

@lizhuomeng71 Thanks, it is fixed and PR has been updated. Ready for testing.

2024-10-11 20:46 UTC, lizhuomeng71 commented
This issue is verified on react and angular

2024-10-15 15:26 UTC, chrisolsen requested changes

2024-10-15 15:26 UTC, chrisolsen commented on libs/react-components/src/lib/dropdown/dropdown.tsx
> +      width={props.width || (!hasDropdownItems ? "100%" : undefined)}
Is this logic needed here? Ideally all logic should exist within the web-component.

2024-10-15 15:26 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    }
Since the `_width` has been made to be reactive, I don't think this block of code is required.

2024-10-15 15:26 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    if (!width && _options.length > 0) {
`bind` is only called after an event, containing an option, has been received, so this additional check is not needed.

2024-10-15 15:26 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +      width: ${_width};
The setting of the style width is already being done within the styles via the `--width` css value being set, but is also being set based on the screen size via the `@media` rule.

2024-10-15 15:26 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +        : getLongestChildWidth(_options) || undefined}
Does it make sense to set a width and a max-width?

2024-10-15 18:19 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    }
PR Updated

2024-10-15 18:19 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    if (!width && _options.length > 0) {
PR Updated

2024-10-15 18:23 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +        : getLongestChildWidth(_options) || undefined}
If we dont set the maxwidth from within the dropdown component, the popover width can extend up to a maximum of 320px.

2024-10-15 19:00 UTC, syedszeeshan commented on libs/react-components/src/lib/dropdown/dropdown.tsx
> +      width={props.width || (!hasDropdownItems ? "100%" : undefined)}
PR has been updated.

2024-10-15 19:00 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    }
PR has been updated.

2024-10-15 19:00 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    if (!width && _options.length > 0) {
PR has been updated.

2024-10-15 19:00 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +      width: ${_width};
PR has been updated.

2024-10-15 22:54 UTC, syedszeeshan commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +        : getLongestChildWidth(_options) || undefined}
Not setting the maxwidth from the dropdown component anymore. Rather, updated the logic in the Popover componentm, as discussed.

2024-10-16 17:28 UTC, syedszeeshan commented on libs/web-components/src/components/popover/Popover.svelte
> +  }
Replaced with this `style("max-width", width ? `max(${width}, ${maxwidth})` : maxwidth),`

2024-10-16 17:29 UTC, syedszeeshan commented on libs/web-components/src/components/popover/Popover.svelte
> +  let _effectiveMaxWidth: string;
replaced with `style("max-width", width ? `max(${width}, ${maxwidth})` : maxwidth),`

2024-10-17 14:38 UTC, chrisolsen commented on libs/web-components/src/components/popover/Popover.svelte
> -
Keep this in. It serves as a reminder for others to keep the code a little orgnanized.

2024-10-17 14:53 UTC, syedszeeshan commented on libs/web-components/src/components/popover/Popover.svelte
> -
PR updated.

2024-10-17 16:04 UTC, lizhuomeng71 commented
this issue is verified on react and angular

2024-10-17 19:58 UTC, chrisolsen approved these changes

2024-10-17 22:09 UTC, ArakTaiRoth approved these changes

2024-10-17 22:09 UTC, merged

2024-10-17 22:16 UTC, tzuge commented
:tada: This PR is included in version 1.17.0-alpha.114 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.17.0-alpha.114)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.17.0-alpha.114)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-22 22:10 UTC, tzuge commented
:tada: This PR is included in version 5.0.0-alpha.10 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/5.0.0-alpha.10)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v5.0.0-alpha.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-30 21:55 UTC, tzuge commented
:tada: This PR is included in version 1.28.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.28.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.28.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-10-30 21:55 UTC, tzuge commented
:tada: This PR is included in version 5.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/5.3.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v5.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-09 19:40 UTC, tzuge commented
:tada: This PR is included in version 3.0.0-alpha.9 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/3.0.0-alpha.9)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v3.0.0-alpha.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-19 17:00 UTC, tzuge commented
:tada: This PR is included in version 3.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/3.2.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v3.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: