fix(#2211): filterable dropdown selected option
GovAlta/ui-components pull request #2303
Opened 2024-12-10 19:05 UTC by BumbleB2na

# Before (the change)

Filterable dropdown selected option broken when a) clicking an option to select, b) using arrows keys to highlight an option then pressing Enter to select, and c) when filterable dropdown input loses focus. Also, selected option in the DOM would not have "aria-selected=true".

# After (the change)

Filterable dropdown selected option fixed when a) clicking an option to select, b) using arrows keys to highlight an option then pressing Enter to select, and c) when filterable dropdown input loses focus. Also, selected option in the DOM has "aria-selected=true".

## Make sure that you've checked the boxes below before you submit the PR

- [x] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [x] I have created necessary unit tests
- [x] I have tested the functionality in both React and Angular.

## Steps needed to test

Testing considerations: Tested UI in Chrome. Did not test behavior of Chrome browser autofill on filterable dropdown input.

2024-12-13 17:34 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +          break;
Since the `onEnter` function is already being called in the keyup event add it here will result in it being called twice.

2024-12-13 17:34 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    setDisplayedValue();
This is replacing a lot of logic (that should've had a comment), but from the commit it was there to prevent dropdown from firing _change event when the value is reselected.

Can we verify this [previous bug fix](https://github.com/govalta/ui-components/issues/1954)  isn't being undone

2024-12-13 17:34 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.spec.ts
> +      option?.addEventListener("click", (e: Event) => {
Is it necessary to override the click event of the dropdown item, as there are other tests on this page that don't?

2024-12-13 17:34 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.spec.ts
> +      });
This is another place that were adding/overriding event handlers within the component. If without it we can't get the test to work because of a limitation of the testing-library then the test will be ok until we shift over to the headless tests, then this test needs to be changed.

This would be a good test to rewrite now in the headless testing branch.

2024-12-13 17:35 UTC, chrisolsen commented
Can you prefix your first two commits in this PR with `chore: `

2024-12-13 21:41 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    setDisplayedValue();
Yes that previous fix is still good. Checked again, but also noticed that previous fix in git history and tested for it before. The `setDisplayedValue()` resets the input to the last selected value or empty string and that's what prevents re-selecting.

2024-12-13 21:42 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    setDisplayedValue();
To clarify what was checked exactly: it does not reach this onChange handler when reselecting

2024-12-13 21:54 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.spec.ts
> +      option?.addEventListener("click", (e: Event) => {
No it wasn't necessary. Thanks and removed some `await tick()` from the other new tests.

2024-12-13 21:58 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +          break;
Thanks was able to remove it from keyup, so now it's been "moved" from keyup to keydown.

2024-12-13 21:59 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.spec.ts
> +      });
Could not easily remove it and like the idea of tackling this in other headless branch that's in progress

2024-12-16 16:52 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +        console.log('enter3')
Just remove the console.log calls (three of them)

2024-12-18 02:03 UTC, chrisolsen requested changes
The commits need to be squashed.

2024-12-19 01:05 UTC, chrisolsen submitted a review, later dismissed

2025-01-09 22:21 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> -          on:change={onChange}
You should talk to Vanessa about this change as the `_onChange` event was previously added to properly handle autofilled data changes.

2025-01-14 00:32 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> -          on:change={onChange}
Please try again. It handles onChange event again to support browser autofill

2025-01-27 20:51 UTC, BumbleB2na commented
Demonstration of how #2304 was resolved:
<video src="https://github.com/user-attachments/assets/b889f136-f46e-4f62-b00a-ee2194e59833" width="200"></video>

2025-01-27 23:46 UTC, ArakTaiRoth commented
@BumbleB2na This was tied also to story #2304 . However, that issue isn't fixed for non-filterable Dropdowns.

2025-01-29 23:08 UTC, BumbleB2na commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> -    if (!_filterable) return;
Resolves https://github.com/GovAlta/ui-components/pull/2303#issuecomment-2617184496 because, basic dropdown was working same as filterable dropdown re: scroll to selected option

2025-02-18 20:39 UTC, BumbleB2na commented
@vanessatran-ddi thank you it's now ready to be re-tested

2025-02-19 20:48 UTC, BumbleB2na commented
@vanessatran-ddi it's fixed now

2025-02-19 23:52 UTC, BumbleB2na commented
Thank you, @vanessatran-ddi will be adding test coverage for clearing selected after backspace completely. Then building on test coverage for autofill that was added earlier in this PR so that it will cover use case such as Country and State/Province dynamic selection. E.g. One dropdown dynamically populates another (or swaps dropdown with input field if no match on first dropdown) and autofill must continue to work on dynamic dropdown or input.

2025-02-27 21:51 UTC, syedszeeshan approved these changes

2025-03-06 00:00 UTC, merged

2025-03-06 00:04 UTC, tzuge commented
:tada: This PR is included in version 1.32.1-alpha.4 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.32.1-alpha.4)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.32.1-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-03-13 21:52 UTC, tzuge commented
:tada: This PR is included in version 4.2.1-alpha.5 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/4.2.1-alpha.5)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v4.2.1-alpha.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-03-20 17:27 UTC, tzuge commented
:tada: This PR is included in version 1.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/ui-components-common/v/1.2.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/common-v1.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-03-20 17:27 UTC, tzuge commented
:tada: This PR is included in version 4.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/4.2.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v4.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-03-20 17:27 UTC, tzuge commented
:tada: This PR is included in version 1.32.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.32.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.32.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-03-20 17:30 UTC, tzuge commented
:tada: This PR is included in version 6.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/6.2.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v6.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: