NOT READY - fix(#2200): textarea width issues
GovAlta/ui-components pull request #2308
Opened 2024-12-13 22:02 UTC by syedszeeshan

# Before (the change)

# After (the change)

## Make sure that you've checked the boxes below before you submit the PR

- [ ] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [ ] I have tested the functionality in both React and Angular.

## Steps needed to test

2024-12-16 19:27 UTC, syedszeeshan commented
![image](https://github.com/user-attachments/assets/f7d2f2d3-6c79-442f-9594-f0536c12d9ae)

2024-12-19 01:20 UTC, chrisolsen commented on libs/web-components/src/components/text-area/TextArea.svelte
> +    display: block;
`inline-block` might be a better choice as it will allow for the setting of the width, but doesn't break the textarea's default behaviour (native textarea is also inline-block)

2024-12-19 01:20 UTC, chrisolsen commented on libs/web-components/src/components/text-area/TextArea.svelte
> +    width: 100%;
Ideally, this width is the one that should be set, but since it is within the :host scope it can't be set via css vars. However, there is a, `injectCss` helper method that will create :host block with the desired value.

```
    injectCss(rootEl, ":host", { width });
```

2024-12-19 16:33 UTC, BumbleB2na requested changes

2024-12-19 16:33 UTC, BumbleB2na commented on libs/web-components/src/components/text-area/TextArea.svelte
>      }
```suggestion
```
Based on some testing done those styles can be removed because the max-width style on Line 249 controls width.

Tested in react playground and in playground\web\src\pages\TextareaPage.svelte:
`<goa-textarea name="item" value="read this" width="75%"></goa-textarea>`

Try removing those styles and if it works for you, too then it looks like Lines 212-259 can be simplified even more:
```
  .root {
    position: relative;
    width: var(--width, 100%);
    padding-bottom: var(--char-count-padding);
    border: var(--goa-border-width-s) solid var(--goa-color-greyscale-700);
    border-radius: 3px;
    transition:
      width 0.3s ease-in-out,
      box-shadow 0.2s ease;
  }
  
  @container self (--mobile) {
    .root {
      width: 100%;
    }
  }

  textarea {
    display: block;
    box-sizing: border-box;
    outline: none;
    border: none;
    border-radius: 3px;
    color: var(--goa-color-greyscale-black, #ccc);
    padding: var(--textarea-padding-vertical) var(--textarea-padding-horizontal);
    font-size: var(--goa-font-size-4);
    font-family: var(--goa-font-family-sans);
    width: 100%;
    resize: vertical;
  }
```

2025-01-09 14:46 UTC, syedszeeshan commented on libs/web-components/src/components/text-area/TextArea.svelte
> +    display: block;
PR updated

2025-01-09 14:46 UTC, syedszeeshan commented on libs/web-components/src/components/text-area/TextArea.svelte
> +    box-sizing: border-box;
PR updated

2025-01-09 14:46 UTC, syedszeeshan commented on libs/web-components/src/components/text-area/TextArea.svelte
>      }
PR updated

2025-01-09 14:46 UTC, syedszeeshan commented on libs/web-components/src/components/text-area/TextArea.svelte
> +    width: 100%;
PR updated

2025-01-14 18:08 UTC, BumbleB2na approved these changes

2025-01-14 19:13 UTC, merged

2025-01-14 19:16 UTC, tzuge commented
:tada: This issue has been resolved in version 1.17.0-alpha.133 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.17.0-alpha.133)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.17.0-alpha.133)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-17 21:42 UTC, tzuge commented
:tada: This issue has been resolved in version 1.30.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.30.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.30.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-21 16:44 UTC, tzuge commented
:tada: This issue has been resolved in version 4.0.1-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/4.0.1-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v4.0.1-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-21 17:41 UTC, tzuge commented
:tada: This issue has been resolved in version 4.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/4.0.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v4.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-21 17:42 UTC, tzuge commented
:tada: This issue has been resolved in version 6.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/6.0.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v6.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-29 17:13 UTC, tzuge commented
:tada: This issue has been resolved in version 1.1.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/ui-components-common/v/1.1.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/common-v1.1.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-29 18:44 UTC, tzuge commented
:tada: This issue has been resolved in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/ui-components-common/v/1.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/common-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: