fix: release workflow - update release workflow for major release
GovAlta/ui-components pull request #2322
Opened 2024-12-23 18:52 UTC by vanessatran-ddi

Fix lint step failed 
![image](https://github.com/user-attachments/assets/185783df-3ba3-4060-9f0d-affe22f27f76)

2024-12-23 18:55 UTC, chrisolsen approved these changes

2024-12-23 19:39 UTC, chrisolsen requested changes
Looks like there are some failing tests

2024-12-23 19:49 UTC, BumbleB2na submitted a review, later dismissed

2024-12-23 20:19 UTC, chrisolsen approved these changes

2024-12-23 20:19 UTC, merged

2024-12-23 20:22 UTC, tzuge commented
:tada: This issue has been resolved in version 3.0.0-alpha.10 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/3.0.0-alpha.10)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v3.0.0-alpha.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-23 20:22 UTC, tzuge commented
:tada: This issue has been resolved in version 1.17.0-alpha.130 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.17.0-alpha.130)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.17.0-alpha.130)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-23 20:22 UTC, tzuge commented
:tada: This issue has been resolved in version 5.0.0-alpha.16 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/5.0.0-alpha.16)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v5.0.0-alpha.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-07 18:40 UTC, tzuge commented
:tada: This issue has been resolved in version 4.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/4.0.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v4.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-01-07 18:40 UTC, tzuge commented
:tada: This issue has been resolved in version 6.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/6.0.0-alpha.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v6.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: