Checkbox component minor fixes with unit tests and storybook entry. This also defers implementation of indeterminate state
GovAlta/ui-components pull request #434
Opened 2022-03-04 19:38 UTC by bluekurinji

2022-03-04 20:31 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +import { onMount } from "svelte";
remove this if it is no longer used

2022-03-04 20:33 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    {#if isIndeterminate}
Maybe revert these changes for now. The way it was initially designed was that the indeterminate prop is a static setting defining if it will show the [-] icon when checked, instead of the `indeterminate` flag also being a checked state value.

2022-03-04 20:37 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<goa-checkbox text="Winter Picnic" value="fun" indeterminate></goa-checkbox>`} lang="html" />
Lots of the examples are using the removed indeterminate flag

2022-03-04 20:38 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<goa-checkbox text="World Peace" value="life" checked></goa-checkbox>`} lang="html" />
The snippet for web components should show how to bind to the exposed event

2022-03-04 20:39 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<goa-checkbox text="World Peace" value="life" checked></goa-checkbox>`} lang="html" />
The snippet for angular components should show how to bind to the exposed event

2022-03-04 20:40 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<GoACheckbox text="Drink and Drive" value="irresponsible and dangerous" error></GoACheckbox>`} lang="jsx" />
needs to show binding to the React event.  Ideally instead of grouping all the examples into one set of tabs it might be better to break up the event binding into a section of it's own with it's own code snippets.

2022-03-04 20:41 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +## Spacing & Padding
From now on, the design documentation from here down shouldn't be included for the alpha releases.

2022-03-04 20:42 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<goa-checkbox text="Winter Picnic" value="fun" indeterminate></goa-checkbox>`} lang="html" />
Indterminate info is also included in one of the images that will need to be removed.

2022-03-09 16:11 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +<Note type="do">
Keep the notes for now

2022-03-09 16:13 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +## Spacing & Padding
Remove the spacing and padding and the Usage

2022-03-09 16:13 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +### disabled
The headings should be capitalized

2022-03-09 16:13 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +### checked
The headings should be capitalized

2022-03-09 16:17 UTC, chrisolsen requested changes
For the markdown that is removed that contains img references can you also remove the corresponding image.

2022-03-09 16:19 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    {#if isIndeterminate}
Remember to revert these changes

2022-03-09 16:27 UTC, chrisolsen commented on libs/react-components/src/lib/checkbox/checkbox.spec.tsx
> +    fireEvent(checkbox, new CustomEvent('_change', { detail: { data: { value: "bar" } } }));
The reason that this test passes is that the event detail data is not validated. Can you add this validation to the test? Checkout the input.spec.tsx for how it is done.

2022-03-09 16:27 UTC, chrisolsen commented on libs/react-components/src/lib/checkbox/checkbox.spec.tsx
> +    fireEvent(checkbox, new CustomEvent('_change', { detail: { data: { value: "bar" } } }));
https://github.com/GovAlta/ui-components/blob/alpha/libs/react-components/src/lib/input/input.spec.tsx

2022-03-14 14:24 UTC, chrisolsen requested changes
There are still a couple of unresolved items.

2022-03-16 17:42 UTC, bluekurinji commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    {#if isIndeterminate}
As checkbox is tristate control, it should not be in indeterminate=true and checked=true state.  The initial design is incorrect. So I am leaving the above code change as is.

2022-03-16 18:06 UTC, chrisolsen commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    {#if isIndeterminate}
After checking out the mui example this change does make sense, and because of that, it then makes sense to revert the hard coded false value set on line 23.

2022-03-16 18:54 UTC, bluekurinji commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    {#if isIndeterminate}
As indeterminate is a calculated state based on it's children checkbox states, based on our earlier decision, indeterminate is not exposed. we can stick with our decision of deferring it for now as children are not implemented yet.

2022-03-21 15:19 UTC, bluekurinji commented on libs/web-components/src/components/checkbox/Checkbox.svelte
> +    {#if isIndeterminate}
Also due to priority and scope changes,  indeterminate implementation is on hold. For now, indeterminate is not exposed.

2022-03-21 17:24 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<goa-checkbox name="desserts" text="Ice Cream" value="10"></goa-checkbox>`} lang="html" />
These examples, as we were discussing with the GoAInput, need to allow the user to copy/paste the code and have it working.

2022-03-21 22:45 UTC, bluekurinji commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +    <CodeSnippet code={`<goa-checkbox name="desserts" text="Ice Cream" value="10"></goa-checkbox>`} lang="html" />
examples are updated as suggested

2022-03-21 22:54 UTC, chrisolsen approved these changes

2022-03-21 22:56 UTC, merged

2022-03-22 22:15 UTC, tzuge commented
:tada: This PR is included in version 3.4.0-alpha.31 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/3.4.0-alpha.31)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v3.4.0-alpha.31)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-22 22:16 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.26 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.26)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.26)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-23 19:06 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.4 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.4)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 22:02 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:47 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:53 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 00:06 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:19 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: