feat: textarea
GovAlta/ui-components pull request #471
Opened 2022-03-14 21:02 UTC by chrisolsen

2022-03-15 21:01 UTC, bluekurinji requested changes

2022-03-15 21:01 UTC, bluekurinji commented on libs/docs/src/components/common/TextArea.stories.mdx
> +## Basic
To be consistent with other component story page, please add `<Story name="Basic">`

2022-03-15 21:07 UTC, chrisolsen commented on libs/web-components/src/components/text-area/TextArea.svelte
> +    if (disabled) return;
It is :) It was unexpected, but the event was firing when I was testing it, which is why it was added.

2022-03-17 20:16 UTC, bluekurinji commented on libs/web-components/src/components/text-area/TextArea.svelte
> +  id={id || name}
Can we make it consistent as done in checkbox. id as "id-" + name ? just to be consistent?

2022-03-17 20:45 UTC, bluekurinji approved these changes

2022-03-17 20:59 UTC, merged

2022-03-17 21:07 UTC, tzuge commented
:tada: This PR is included in version 3.4.0-alpha.25 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/3.4.0-alpha.25)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v3.4.0-alpha.25)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-17 21:08 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.21 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.21)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.21)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-21 20:44 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.3 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.3)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 22:02 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:47 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:53 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 00:06 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:20 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: