fix(#708): initial values not being visible in dropdown
GovAlta/ui-components pull request #744
Opened 2022-06-22 22:23 UTC by chrisolsen

2022-06-23 21:10 UTC, bluekurinji requested changes

2022-06-23 21:10 UTC, bluekurinji commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +          const selected = _values.includes(_data.value);
we have data and _data variables. Lets keep the naming consistent. Avoid using this sort of a pair as we dont have any defined meaning to variables starting with _

2022-06-23 21:10 UTC, bluekurinji commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +
We need to talk with designers for the need for keeping width as per the max item width. If they say yes, we may need to move this width calculating util somewhere for consistent usage in other components

2022-06-23 21:10 UTC, bluekurinji commented on libs/react-components/src/lib/dropdown/dropdown.tsx
>    multiselect?: boolean;
Need to hide multiselect for now

2022-06-23 22:14 UTC, bluekurinji commented
The story book does not have some then exposed properties in the code samples like disabled, leadingicon and placeholder

2022-06-23 22:25 UTC, bluekurinji commented on libs/web-components/src/components/dropdown/Dropdown.spec.ts
> +    // show menu
Right now, the presence of error is asserted. For better coverage, we also need to assert absence of the error as well. The placement of absence of error assertion could be done in 'should render' test as it is an excellent place for asserting all the default state of an component

2022-06-23 22:25 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> -  export let maxheight: number = MAX_HEIGHT;
This height is for the option menu and a width is required.

2022-06-23 22:25 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +  export let multiselect: boolean = false;
It isn't in the docs so it is ok.

2022-06-23 22:26 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +  let _values: string[] = [];
This is a private var

2022-06-23 22:27 UTC, bluekurinji commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +
Looks like, design team to come up with very specific details about how width can be defined. It is out of the scope of this ticket

2022-06-23 22:27 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +          const selected = _values.includes(_data.value);
because `data` is already declared in the current scope.

2022-06-23 22:28 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +
This is the only component that needs to compute the max item width, if they choose to do so.

2022-06-23 22:53 UTC, chrisolsen commented on libs/react-components/src/lib/dropdown/dropdown.tsx
>    multiselect?: boolean;
It isn't in storybook so I think that is sufficient for now

2022-06-24 07:36 UTC, bluekurinji commented
Storybook Example for basic should change into

export class MyComponent {
  colors: string[] = ['red', 'green', 'blue'];
  selectedColor: string[] = ['red'];
  selectColor(event: any) {
    this.selectedColor = event.detail.value;
  }
}

2022-06-24 07:40 UTC, bluekurinji commented
As per the react code green should be displayed as selected item. As per angular code red should be the selected item. That needs a correct

2022-06-24 07:48 UTC, bluekurinji commented
When same name is applied for more than one dropdown in the same page accidently,  like below 

```typescript 
<h3>Dropdown</h3>
<goa-dropdown
  name="colors"
  placeholder="Select a user"
  [value]="selectedColor"
  (_change)="selectColor($event)"
>
  <goa-dropdown-item
    name="colors"
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  >
  </goa-dropdown-item>
</goa-dropdown>

<h3>Error</h3>
<goa-dropdown name="colors" placeholder="Select a user" error="true">
  <goa-dropdown-item value="red" name="colors" label="Red"></goa-dropdown-item>
  <goa-dropdown-item
    value="green"
    name="colors"
    label="Green"
  ></goa-dropdown-item>
  <goa-dropdown-item
    value="blue"
    name="colors"
    label="Blue"
  ></goa-dropdown-item>
</goa-dropdown>
```

The console error is not helpful. 
1. The re should be helpful error suggestion
2. Also, leave a note in storybook for developers

![image](https://user-images.githubusercontent.com/2401903/175488982-72cbf935-3d65-4c8a-9f61-bbf34ea9df7a.png)

2022-06-24 07:50 UTC, bluekurinji commented
In storybook, the angular example does not match react example. example placeholder is used in one and another does not

2022-06-27 16:14 UTC, bluekurinji commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +  let _values: string[] = [];
Lets pass it for now

2022-06-27 17:54 UTC, merged

2022-06-27 18:03 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.14 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.14)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.14)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-06-27 18:04 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.72 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.72)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.72)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-06-27 18:32 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.13 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.13)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 21:57 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:43 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:49 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 00:02 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:15 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: