fix!(DDI-675): refactor footer
GovAlta/ui-components pull request #771
Opened 2022-07-13 21:07 UTC by chrisolsen

2022-07-14 04:36 UTC, bluekurinji commented
Please update reactdemo app.tsx as follows. It was not running locally for me

``reactjs
import { GoAAppHeader, GoAAppFooter, GoAButton, GoAButtonGroup, GoACheckbox, GoAFormItem, GoAInput, GoAPageBlock, GoARadioGroup, GoARadioItem, GoAMicrositeHeader, GoAAppFooterNavSection, GoAAppFooterMetaSection } from "@abgov/react-components";
import { useState } from "react";
export function App() {

  const [firstName, setFirstName] = useState<string>('');
  const [desserts, setDesserts] = useState(false);

  function submitForm(e: any) {
    console.log('submitForm', firstName);
    e.preventDefault();
  }

  function onRadioChange(name: string, value: string) {
    console.log('onRadioChange', name, value);
  }

  return (
    <>
      <GoAMicrositeHeader level="alpha" version="UAT" />

      <GoAAppHeader url="http://google.com" title="Digital File Service">
        <a href="#">Sign in</a>
      </GoAAppHeader>

      <GoAPageBlock width="704px">
        <form>
          <GoAFormItem label="First Name">
            <GoAInput id="firstname" name="firstname" type="text" value={firstName} onChange={(_name, value) => setFirstName(value)} />
          </GoAFormItem>

          <GoACheckbox
            name="desserts"
            text="Ice Cream"
            value="10"
            checked={desserts}
            onChange={(name, checked, value) => {
              setDesserts(checked);
              console.log(name, checked, value);
            }}
          />

          <GoAButtonGroup alignment="start">
            <GoAButton type="primary" onClick={submitForm}>Submit</GoAButton>
          </GoAButtonGroup>
        </form>
      </GoAPageBlock>

      <GoARadioGroup name="basic" value="orange" onChange={onRadioChange}>
        <GoARadioItem name="basic" label="Red" value="red" />
        <GoARadioItem name="basic" label="Blue" value="blue" />
        <GoARadioItem name="basic" label="Orange" value="orange" />
      </GoARadioGroup>

      <GoAAppFooter>
        <GoAAppFooterNavSection name="All Services">
          <a href="a.html">Arts and culture</a>
          <a href="b.html">Education and training</a>
          <a href="c.html">Family and social supports</a>
          <a href="d.html">Housing and community</a>
          <a href="e.html">Life events</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterNavSection name="Social Media">
          <a href="instagram.html">Instagram</a>
          <a href="youtube.html">YouTube</a>
          <a href="facebook.html">Facebook</a>
          <a href="snapchat.html">Snapchat</a>
          <a href="twitter.html">Twitter</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterMetaSection>
          <a href="privacy.html">Privacy</a>
          <a href="disclaimer.html">Disclaimer</a>
          <a href="accessibility.html">Accessibility</a>
          <a href="using-alberta.html">Using Alberta.ca</a>
        </GoAAppFooterMetaSection>
      </GoAAppFooter>
    </>
  );
}

export default App;

``

2022-07-14 04:53 UTC, bluekurinji commented
The svelte local app is not displaying footer properly. Not sure why. It making code review difficult.

2022-07-14 05:03 UTC, bluekurinji commented
The default footer has unwanted divider

2022-07-14 05:05 UTC, bluekurinji commented
The meta is not getting displayed as per design 

![image](https://user-images.githubusercontent.com/2401903/178903394-3bec9e72-40b0-4ce4-8ad6-ead4bc004d05.png)

2022-07-14 12:22 UTC, chrisolsen commented
> The meta is not getting displayed as per design
> 
> ![image](https://user-images.githubusercontent.com/2401903/178903394-3bec9e72-40b0-4ce4-8ad6-ead4bc004d05.png)

Make sure you re-build the styles for this one.

2022-07-14 19:50 UTC, bluekurinji commented
> > The meta is not getting displayed as per design
> > ![image](https://user-images.githubusercontent.com/2401903/178903394-3bec9e72-40b0-4ce4-8ad6-ead4bc004d05.png)
> 
> Make sure you re-build the styles for this one and the footer not displaying right in the svelte testing app.

I built style and ran the react Demo in this pull request. I see it

2022-07-14 19:52 UTC, bluekurinji commented
> > The default footer has unwanted divider
> > ![image](https://user-images.githubusercontent.com/2401903/178903208-0ed2b497-37e9-4d1d-b4d3-94f1d325255a.png)
> 
> Where are you seeing this example? In storybook? If you are manipulating the code and it live reloads you will need to hard reload the browser to ensure that the component's state is not stale.
> 
> I don't see this in the react app ![image](https://user-images.githubusercontent.com/41582/178982771-1cd0f9b1-e250-4ccc-b016-b8c087cbf793.png)

The skeleton app is not found in this pull request. In this pull request react demo, I see this issue

2022-07-14 19:52 UTC, bluekurinji requested changes

2022-07-14 19:52 UTC, bluekurinji commented on libs/web-components/src/components/footer/Footer.svelte
> +  </footer>
The nested footer is not recommended practice. This needs to be fixed.

![image](https://user-images.githubusercontent.com/2401903/179070432-08b9de37-06ec-4f7f-8cce-a1bcd93fad8d.png)

2022-07-15 22:09 UTC, chrisolsen commented on libs/web-components/src/components/footer-meta-section/FooterMetaSection.svelte
> +<slot />
task will be created for this

2022-07-15 22:16 UTC, chrisolsen commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +    (rootEl?.parentNode as ShadowRoot)?.appendChild(style);
will check on my side

2022-07-15 22:20 UTC, chrisolsen commented on libs/web-components/src/components/footer-meta-section/FooterMetaSection.svelte
> +<slot />
create a task for this to move these links into the shadow dom

2022-07-19 15:52 UTC, bluekurinji requested changes

2022-07-19 15:52 UTC, bluekurinji commented on libs/web-components/src/components/footer/Footer.svelte
> +      <a href="https://alberta.ca" class="goa-copyright">© {year} Government of Alberta</a>
Is this as per the design?

![image](https://user-images.githubusercontent.com/2401903/179792660-69eece94-f88b-4a39-985b-67f424846f3d.png)

2022-07-19 15:52 UTC, bluekurinji commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +      --column-count: ${columncount};
Just a discussion:  Is this as per the design 

![image](https://user-images.githubusercontent.com/2401903/179794271-f335fb34-a05e-4009-a0b6-eae28f0d21a3.png)

2022-07-19 16:50 UTC, bluekurinji requested changes

2022-07-19 16:50 UTC, bluekurinji commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +      --display-type: ${columncount > 1 ? "block" : "flex"};
The earlier-implementation / design-recommendation had the columns number decreasing by one each time as the viewport's width is decreasing. Since, it was done earlier, why to miss it out now? 

In case, if team agrees to do it later, the columnCount should be named as "maxColumnCount". As the number of columns is going to decrease based on view port, maxColumnWidth indicates  that to enduser. Or any other naming that communicates the number of column width change is good. 

irrespective of when it is to be done, the naming has to change now. Otherwise, it will be a breaking change.

2022-07-19 17:59 UTC, bluekurinji commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +    style={`
And this also need to be addressed. "Business and Economy" and "Emergencies and public safety" are broken into three lines when it wraps.

![image](https://user-images.githubusercontent.com/2401903/179817944-f21f600a-4302-4c06-a1e1-d8a5febce432.png)

2022-07-19 18:17 UTC, bluekurinji commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +    style={`
well done

2022-07-19 18:20 UTC, bluekurinji commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +      --column-count: ${columncount};
Please create a ticket, if Tom takes his time to respond to this design. This need not holds the pull request merge

2022-07-19 21:21 UTC, ArakTaiRoth commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +      --column-count: ${columncount};
Story has been made, here https://goa-dio.atlassian.net/browse/DDIDS-860?atlOrigin=eyJpIjoiNWMxZjNhMzIyZTBiNDdiZWEzYTE0ZjgyMmY5NTE1NjkiLCJwIjoiaiJ9

2022-07-19 21:23 UTC, ArakTaiRoth commented on libs/web-components/src/components/footer-nav-section/FooterNavSection.svelte
> +      --display-type: ${columncount > 1 ? "block" : "flex"};
Looks like this is done, @bluekurinji can you resolve this if everything is good.

2022-07-20 15:39 UTC, bluekurinji approved these changes

2022-07-20 16:12 UTC, merged

2022-07-21 16:42 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.19 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.19)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-21 16:43 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.76 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.76)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.76)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-18 02:07 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.15 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.15)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 21:57 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:42 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:48 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 00:01 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:14 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: