fix: allow for default props to circular progress component
GovAlta/ui-components pull request #776
Opened 2022-07-20 18:06 UTC by chrisolsen

DDI-765: add docs for the new default props

2022-07-20 19:29 UTC, bluekurinji commented
Please refer the ticket number in the commit :-)

2022-07-20 19:29 UTC, bluekurinji approved these changes

2022-07-20 19:29 UTC, bluekurinji commented on libs/docs/src/components/common/CircularProgress.stories.mdx
> +      <goa-circular-progress (visible)="visible"></goa-circular-progress>
This should be 
`<goa-circular-progress [visible]="visible"></goa-circular-progress>`

2022-07-20 19:40 UTC, bluekurinji requested changes

2022-07-20 19:40 UTC, bluekurinji commented on libs/docs/src/components/common/CircularProgress.stories.mdx
> +      <goa-circular-progress (visible)="visible"></goa-circular-progress>
missed the above change request and approved it by mistake

2022-07-20 20:50 UTC, chrisolsen commented
> [DDI-765](https://goa-dio.atlassian.net/browse/DDIDS-765): add docs for the new default props

The storybook issue is referenced in the commit message, just not the first line for reason that this PR is mainly adding default values, which previously did not exist.

2022-07-21 16:26 UTC, bluekurinji approved these changes

2022-07-21 16:33 UTC, merged

2022-07-21 16:42 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.19 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.19)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-21 16:43 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.76 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.76)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.76)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-18 02:07 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.15 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.15)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 21:57 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:42 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:48 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 00:01 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:14 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: