791 container story updates
GovAlta/ui-components pull request #836
Opened 2022-08-26 22:07 UTC by chrisolsen

2022-08-27 00:53 UTC, ArakTaiRoth requested changes

2022-08-27 00:53 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Container.stories.mdx
> +Non-interactive containers indicate that the content is only for the user to review. Use a grey accent to indicate that there is content in the container that the content is not interactive.
I know this is nitpicky and I'm sorry. But can you add `and` in between `the container` and `that the content`. Without it, that sentence looks weird.

2022-08-27 00:53 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Container.stories.mdx
> +There are three main types within the interactive and non-interactive container types: a large accent bar, a small accent bar, and a accent bar with text.
Should be `and AN accent bar with text`

2022-08-27 00:53 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Container.stories.mdx
> +  <>
What's this?

2022-08-27 00:53 UTC, ArakTaiRoth commented on libs/docs/src/components/common/Container.stories.mdx
> +#### Alternate color for default container
Couple things, should be `colour`, not `color`.
Also, just a question about this alternate colour option. It looks like it's used with the `colored` option (should also be `coloured`). But that doesn't indicate what colour it's using or anything. Would it not be better to have an option where a user could supply their own alternative colour in a hex format to be used maybe?

2022-08-27 00:53 UTC, ArakTaiRoth commented on libs/react-components/src/lib/container/container.tsx
> +  variant?: ContainerVariant;
Another question. I'm not seeing where the defaults are set for these values that aren't required?

2022-08-27 01:07 UTC, chrisolsen commented on libs/docs/src/components/common/Container.stories.mdx
> +#### Alternate color for default container
We don't give the flexibility to allow them to choose colors, as that would allow them to deviate from the GoA branding.

2022-08-27 01:09 UTC, chrisolsen commented on libs/react-components/src/lib/container/container.tsx
> +  variant?: ContainerVariant;
![image](https://user-images.githubusercontent.com/41582/187008392-2155629a-bd8a-49a9-81ff-fcbf145349d9.png)

2022-08-27 01:11 UTC, chrisolsen commented on libs/docs/src/components/common/Container.stories.mdx
> +#### Alternate color for default container
The doc header should probably be converted to the English spelling, but all code properties follow the US spelling

2022-08-27 01:14 UTC, chrisolsen commented on libs/docs/src/components/common/Container.stories.mdx
> +Non-interactive containers indicate that the content is only for the user to review. Use a grey accent to indicate that there is content in the container that the content is not interactive.
:+1:  This was all copy and pasted from the UI docs

2022-08-29 18:00 UTC, ArakTaiRoth approved these changes

2022-08-29 18:00 UTC, merged

2022-08-29 18:12 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.37 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.37)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.37)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-29 18:13 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.92 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.92)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.92)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-09-21 22:54 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.16 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.16)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 21:54 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:39 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:45 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 23:58 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:11 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: