fix(DDI-924): allow for dynamic data-bindinging to radio and dropdown…
GovAlta/ui-components pull request #846
Opened 2022-08-30 21:42 UTC by chrisolsen

… components

2022-08-30 23:03 UTC, ArakTaiRoth requested changes

2022-08-30 23:03 UTC, ArakTaiRoth commented on libs/web-components/src/components/dropdown/Dropdown.spec.ts
> +      name: 'favcolor2',
It doesn't look like this test cares about the `name` attribute, so just wondering why did we change this?

2022-08-30 23:03 UTC, ArakTaiRoth commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    }, 10);
What's the time between intervals?

2022-08-31 16:26 UTC, chrisolsen commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    }, 10);
10ms

2022-08-31 16:55 UTC, ArakTaiRoth commented on libs/web-components/src/components/dropdown/Dropdown.svelte
> +    }, 10);
Of course, I'm such a dunce, sorry.

2022-08-31 16:56 UTC, ArakTaiRoth approved these changes

2022-08-31 16:56 UTC, merged

2022-08-31 17:11 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.40 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.40)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.40)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-31 17:12 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.95 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.95)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.95)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-09-21 22:53 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.16 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.16)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 21:54 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:39 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:45 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 23:58 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:11 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: