Ddids 881 new tabset for component props
GovAlta/ui-components pull request #905
Opened 2022-09-30 16:14 UTC by Radha-Alberta

Made the component properties same for angular and react.
Updated same in code examples.

2022-09-30 16:51 UTC, chrisolsen requested changes
Looks good. As soon as the conflicts are resolved it can be merged.

2022-09-30 18:39 UTC, chrisolsen approved these changes

2022-09-30 21:09 UTC, ArakTaiRoth approved these changes

2022-09-30 21:09 UTC, merged

2022-09-30 21:31 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.62 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.62)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.62)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-04 21:10 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.108 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.108)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.108)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-06 18:48 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.17 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.17)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.17)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-26 21:51 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.6 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.6)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 21:36 UTC, tzuge commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 22:42 UTC, tzuge commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-07 23:55 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-08 01:09 UTC, tzuge commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: