feat(DDI-1023): Added Notification Banner Storybook doc
GovAlta/ui-components pull request #935
Opened 2022-10-21 18:53 UTC by Radha-Alberta

Added Storyboook page for Notification Banner documentation

2022-10-21 21:52 UTC, chrisolsen requested changes

2022-10-21 21:52 UTC, chrisolsen commented on libs/web-components/src/components/icon-button/IconButton.svelte
> +  export let noeffects: string;
What is the prop for? If we need a button without effects it would probably be a variant rather than an extra prop. This changes is also outside the scope of the ticket, so it should be removed.

2022-10-21 21:52 UTC, chrisolsen commented on libs/web-components/src/components/notification/Notification.spec.ts
> +  ["important", "information", "emergency", "event"].forEach(type => {
We should also be testing to ensure non-valid values show a console error.

2022-10-21 21:52 UTC, chrisolsen commented on libs/web-components/src/components/notification/Notification.svelte
> +  export let testid: string = "";
I want to eliminate the testids being public

2022-11-07 22:45 UTC, chrisolsen commented on libs/web-components/src/components/notification/Notification.svelte
>    }
What is this for?

2022-11-07 22:46 UTC, chrisolsen commented on libs/web-components/src/components/icon-button/IconButton.svelte
> +    color: unset;
I am still not so sure about this.

2022-11-07 22:46 UTC, Radha-Alberta commented on libs/web-components/src/components/notification/Notification.spec.ts
> +  ["important", "information", "emergency", "event"].forEach(type => {
Done

2022-11-07 22:46 UTC, Radha-Alberta commented on libs/web-components/src/components/notification/Notification.svelte
> +  export let testid: string = "";
Removed the testid

2022-11-07 22:47 UTC, chrisolsen commented on libs/web-components/src/components/icon-button/IconButton.svelte
>      medium: "1rem",
Since the calculated size value is always 1rem, let's remove this value and hardcode the 1rem value.

2022-11-07 22:48 UTC, chrisolsen commented on libs/web-components/src/components/icon-button/IconButton.svelte
> +    padding: calc(var(--size) / 4);
Since --size will no longer exist we can put the hardcoded value here

2022-11-08 21:52 UTC, chrisolsen approved these changes

2022-11-09 01:53 UTC, merged

2022-11-09 02:07 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.123 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.123)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.123)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-16 18:22 UTC, tzuge commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-16 18:23 UTC, tzuge commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-29 21:41 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.18 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.18)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-05 18:03 UTC, tzuge commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-12 20:08 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.11 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.11)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-17 18:23 UTC, tzuge commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: