Ddids 1031 callout modal
GovAlta/ui-components pull request #940
Opened 2022-10-27 15:40 UTC by Radha-Alberta

Added callout variants for modal component.

2022-10-27 18:46 UTC, chrisolsen commented on .vscode/launch.json
> -        },
Can you add `.vscode` to the `.gitignore` file to prevent this file from being committed?

2022-10-27 18:47 UTC, chrisolsen commented on apps/angular-demo/src/app/modal/modal.component.html
> +  >
Can you fix up these closing angle brackets?

2022-10-27 18:52 UTC, chrisolsen commented on libs/docs/src/components/common/Modal.stories.mdx
> +      <goa-modal id="modal" heading="Do you agree?" [open]="isOpen">
How is this modal now being closed?

2022-10-27 18:56 UTC, chrisolsen commented on libs/react-components/src/lib/modal/modal.tsx
> +        <div style={{ margin: "1.5rem 0 0" }} slot="actions">
Styling should not be added to the the react component, otherwise there will be inconsistency between it and others.

2022-10-27 18:58 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +  type variant = (typeof CALLOUT_VARIANT_TYPES)[number];
For clarity, let's rename this type to CalloutVariant (capitalized too)

2022-10-27 19:05 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +      {#if type === "callout" && CALLOUT_VARIANT_TYPES.includes(calloutvariant)}
We don't need the second condition since it is already checked within the `onMount` hook function.

2022-10-27 19:06 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +            <goa-scrollable direction="vertical" height="50">
What is the reason this was removed?

2022-10-27 19:10 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +      <span class="content">
Putting `div` elements within `span` tags is not a good practice. Use `display: flex` instead to align them horizontally.

2022-10-27 19:13 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +  /* Modal Title ============================================================================ */
Modal Content

2022-10-27 21:05 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +          <div class="modal-actions" data-testid="modal-actions">
Is there a reason this has been changed? I seem to remember trying something like this before and it didn't work

2022-10-28 16:47 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
>      text-align: right;
Try using `justify-content: end`

2022-10-28 17:09 UTC, Radha-Alberta commented on .vscode/launch.json
> -        },
Added

2022-10-28 17:10 UTC, Radha-Alberta commented on libs/react-components/src/lib/modal/modal.tsx
> +        <div style={{ margin: "1.5rem 0 0" }} slot="actions">
Removed from react and added in web component

2022-10-28 17:10 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +  type variant = (typeof CALLOUT_VARIANT_TYPES)[number];
Done

2022-10-28 17:10 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +  export let calloutvariant: variant = "";
Changed

2022-10-28 17:10 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +      {#if type === "callout" && CALLOUT_VARIANT_TYPES.includes(calloutvariant)}
Removed the condition

2022-10-28 17:10 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +      <span class="content">
Replaced span with div

2022-10-28 17:10 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +  /* Modal Title ============================================================================ */
Changed

2022-10-28 17:11 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +          <div class="modal-actions" data-testid="modal-actions">
Changed the class back to div

2022-10-28 17:11 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
>      text-align: right;
Done

2022-10-28 19:31 UTC, chrisolsen commented on .vscode/launch.json
> +  // Use IntelliSense to learn about possible attributes.
maybe try adding `.vscode/` to the .gitignore file

2022-10-28 19:35 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +          <div class="modal-actions" data-testid="modal-actions">
Looks good. Can you just fix the indentation of this div?

2022-10-28 19:37 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +        <span class="icon {calloutvariant}">
This `span` should also be changed to a `div`

2022-10-28 19:40 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +  goa-icon {
We shouldn't be centering with padding. Use the flex styling props to center it.

2022-10-28 19:41 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +  .icon {
Can you change this name? It seems this class is being applied to the colored sidebar, rather than an icon. So it is a little confusing.

2022-10-28 19:43 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +    pointer-events: none;
The goa-icon should not need this pointer-event style, since it should not be changing the pointer. If it is, then this css attribute should be put within the goa-icon component.

2022-10-28 19:44 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +    justify-content: end;
Since `.modal-actions` isn't a doesn't have a display value of `flex` I don't think this will do anything.

2022-10-28 20:36 UTC, chrisolsen requested changes
Few more issues

2022-10-28 20:39 UTC, chrisolsen commented on libs/react-components/src/lib/modal/modal.tsx
> +        <div style={{ margin: "1.5rem 0 0" }} slot="actions">
I was under the impression that this wasn't going to get added right now seeing as there is no way to determine if the actions slot contains content.

2022-11-01 14:35 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +          <div class="modal-actions" data-testid="modal-actions">
Done

2022-11-01 14:35 UTC, Radha-Alberta commented on .vscode/launch.json
> +  // Use IntelliSense to learn about possible attributes.
Done

2022-11-01 14:36 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +  .icon {
Renamed to callout-bar

2022-11-01 14:50 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +    pointer-events: none;
Removed the pointer-event style

2022-11-01 14:51 UTC, Radha-Alberta commented on libs/web-components/src/components/modal/Modal.svelte
> +    justify-content: end;
Yes. Removed the justify-content style

2022-11-02 13:54 UTC, chrisolsen commented on libs/web-components/src/components/modal/Modal.svelte
> +  .modal-actions:empty {
Good find :+1:

2022-11-02 13:56 UTC, chrisolsen commented
The only thing that needs to be changed is the commit messages. The first commit is a *feat* the second commit is a *chore*

2022-11-03 22:19 UTC, chrisolsen commented on libs/web-components/src/components/form-item/FormItem.svelte
> +    <div class="error-msg">
From a different PR?

2022-11-03 22:35 UTC, chrisolsen approved these changes

2022-11-08 17:18 UTC, chrisolsen approved these changes

2022-11-08 17:19 UTC, merged

2022-11-09 02:07 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.123 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.123)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.123)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-16 18:23 UTC, tzuge commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-11-29 21:41 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.18 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.18)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-05 18:03 UTC, tzuge commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-12 20:08 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.11 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.11)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-17 18:23 UTC, tzuge commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: