feat(DDI-1095): Added reactive binding examples
GovAlta/ui-components pull request #966
Opened 2022-11-23 18:59 UTC by Radha-Alberta

Added reactive binding examples for text area, dropdowns, radio buttons, checkbox and input components.

2022-11-23 19:06 UTC, chrisolsen requested changes

2022-11-23 19:06 UTC, chrisolsen commented on libs/docs/src/components/common/Checkbox.stories.mdx
> +          [formControl]="reactiveFormCtrl"
Why are you changing the way the binding is being done? `[(ngModel]` is the *reactive* method.

https://www.pluralsight.com/guides/difference-between-template-driven-and-reactive-forms-angular

2022-11-30 20:23 UTC, chrisolsen commented on apps/angular-demo/src/app/checkbox/checkbox.component.html
> +  value="IceCream"
I don't think that `value` or `[value]` are required.

2022-11-30 22:03 UTC, Radha-Alberta commented on apps/angular-demo/src/app/checkbox/checkbox.component.html
> +  value="IceCream"
Removed value and [value]

2022-11-30 22:44 UTC, chrisolsen commented on apps/angular-demo/src/app/input-component/input-component.component.html
> +  [value]="reactiveFormCtrl.value"
Looks like you missed a couple

2022-12-01 16:21 UTC, chrisolsen approved these changes

2022-12-01 22:02 UTC, merged

2022-12-05 17:57 UTC, tzuge commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.2.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-05 18:00 UTC, tzuge commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.2.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-05 18:02 UTC, tzuge commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.1.0)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-05 22:39 UTC, tzuge commented
:tada: This PR is included in version 4.0.0-alpha.92 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/react-components/v/4.0.0-alpha.92)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/react-v4.0.0-alpha.92)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-05 22:40 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.132 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/web-components/v/1.0.0-alpha.132)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/web-components-v1.0.0-alpha.132)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-28 05:41 UTC, tzuge commented
:tada: This PR is included in version 1.0.0-alpha.19 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/styles/v/1.0.0-alpha.19)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/styles-v1.0.0-alpha.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-12 20:07 UTC, tzuge commented
:tada: This PR is included in version 2.0.0-alpha.11 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.0-alpha.11)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.0-alpha.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-17 18:22 UTC, tzuge commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@abgov/angular-components/v/2.0.1)
- [GitHub release](https://github.com/GovAlta/ui-components/releases/tag/angular-v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: